server:
  port: 8781
nickname: helloworld
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/mqmalldb?useUnicode=true&characterEncoding=utf8&useSSL=false